### ISSUE TITLE
Hard coded dependencies on java classpath command line

### ISSUE THREAD

**Issue by ClementDanila** [strator-dev/greenpepper#115]
Hello,

It seems that the commons-codec (1.3 version) dependency is hard-coded in the defaultRunner.java.

Therefore inclusion of another version on the SUT classpath of commons-codec might be unused to the benefit of the hard coded version.

extract of generated java command line :
cmd> java -cp .......s-cli-1.2.jar:/opt/maven/localrepository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar:/opt/maven/localrepository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar:/opt/maven/lo.......

the incriminated line could be :
https://github.com/strator-dev/greenpepper/blob/9b6f803b5e9c5edd9f479aba110e964d807a8d8d/greenpepper/greenpepper-server/src/main/java/com/greenpepper/server/database/hibernate/DefaultRunners.java#L195

Thanks a lot

**Comment by wattazoum** [comment]
I will use maven shade plugin to get rid of this conflict

**Comment by wattazoum** [comment]
Fixed by #116
