### ISSUE TITLE
create a public repository for greenpepper

### ISSUE THREAD

**Issue by wattazoum** [strator-dev/greenpepper#14]
Sonatype offers to host a repository for open source projects. 
Follow their procedure and put greenpepper maven binaries there.

**Comment by wattazoum** [comment]
Requests open to https://issues.sonatype.org/browse/OSSRH-17840

**Comment by wattazoum** [comment]
The repository is created !

**Comment by hachicha** [comment]
vquel

**Comment by hachicha** [comment]
sorry closed by mistake ! :)

**Comment by wattazoum** [comment]
[Joel Orlina added a comment](https://issues.sonatype.org/browse/OSSRH-17840?focusedCommentId=329776&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-329776)
> Configuration has been prepared, now you can:
> * Deploy snapshot artifacts into repository https://oss.sonatype.org/content/repositories/snapshots
> * Deploy release artifacts into the staging repository https://oss.sonatype.org/service/local/staging/deploy/maven2
> * Promote staged artifacts into repository 'Releases'
> * Download snapshot and release artifacts from group https://oss.sonatype.org/content/groups/public
>  *Download snapshot, release and staged artifacts from staging group https://oss.sonatype.org/content/groups/staging
> 
> please comment on this ticket when you promoted your first release, thanks
