### ISSUE TITLE
Improve the summary on a greenpepper:run build

### ISSUE THREAD

**Issue by wattazoum** [strator-dev/greenpepper#62]
Currently, we have the following at the end of the build

```
Results for 414 specification(s):
28439 tests: 25578 right, 931 wrong, 2 ignored, 1928 exception(s)

List of failed tests
```

A more interesting output should be
```
Results for 414 specification(s): 300 right, 100 wrong, 10 ignored, 4 not run
```

**Comment by arnor2000** [comment]
The total of specification is the sum of matching specifications of all repositories.
The number of wrong is incremented for each specification with at least one wrong or one exception result.
The number of right is incremented for each specification with no wrong, no exception and at least one right result.
The number of skipped is incremented for each specification in other cases.
The number of not run is the total of specification minus right, wrong and skipped specifications.

**Comment by wattazoum** [comment]
I have created a branch for this issue .

**Comment by arnor2000** [comment]
Here is the pull request: https://github.com/strator-dev/greenpepper/pull/66
