### ISSUE TITLE
List Validation - Improvements

### ISSUE THREAD

**Issue by MathieuGilet** [strator-dev/greenpepper#97]
Add the possibility to check if the values of a list validation column are not null rather than equal.

**Comment by wattazoum** [comment]
Let's add the **?** syntax to a list  to mean that the value should not be null. 

value = null --> failure
nalue != null --> display it in gray

| list of | Accounts |
| ------- | ------------|
| **name** | **surname?** |
| John |  |
| Any | Name |

**Comment by wattazoum** [comment]
Thinking more about it, I prefer a more explicit way like **(keyword)** in the header.


| list of | Accounts | | | 
| ------- | ------------| ---- | ---- | 
| **name** | **surname(not null)** | **debt(null)** | **got money(true)** | 
| John |  | | | 
| Any | Name | | |

**Comment by wattazoum** [comment]
The keyword in the header will define an expected default value. This will be the value expected if the cell is Empty. If the cell is not empty, we should check for the exact expected value.

| list of | Accounts | | | |
| ------- | ------------| ---- | ---- | --- |
| **name** | **surname(not null)** | **debt(null)** | **got money(true)** |  | 
| John |  | | |  
| Any | Name | | | 

Second line is ok, if the SUT returns a suname that is **Name** (and not any value)
